require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colourscheme"
require "user.cmp"
require "user.nvim-webdev-icons"
require "user.nvim-tree"
require "user.autopairs"
require "user.bufferline"
require "user.lualine"
require "user.project"
-- require "user.impatient"
require "user.telescope"
require "user.treesitter"
require "user.gitsigns"
require "user.comment"
require "user.lsp"
require "user.autocommands"
