require "options"
require "keymaps"
require "plugins"
require "colourscheme"
require "lsp"

require "plugconfig.cmp"
require "plugconfig.telescope"
require "plugconfig.treesitter"
require "plugconfig.autopairs"
require "plugconfig.comment"
require "plugconfig.gitsigns"
